# Generated by Django 5.2.18 on 2026-10-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('employment_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self-employed')], max_length=16)),
                ('employer_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=120)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_credit_cards', models.PositiveSmallIntegerField(default=0)),
                ('id_document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('DRIVING_LICENSE', 'Driving licence'), ('SSN', 'Social security number')], max_length=20)),
                ('id_document_number', models.CharField(max_length=24)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_document_type', 'id_document_number'), name='uniq_customer_identity')],
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DOCUMENTS_REQUESTED', 'Additional documents requested')], default='SUBMITTED', max_length=24)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=16)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
