# Generated by Django 5.2.18 on 2026-10-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('VISA', 'Visa')], max_length=16)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_on', models.DateField()),
                ('pin_hash', models.CharField(max_length=128)),
                ('pin_is_default', models.BooleanField(default=True)),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('pin_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='applications.creditapplication')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='applications.customer')),
            ],
        ),
    ]
